### ISSUE TITLE
Investigate if `ios/` & `android/` should be included in `.gitignore`

### ISSUE THREAD

**Issue by ollema** [Hugos68/capkit#69]
See:

https://stackoverflow.com/questions/63084828/gitignore-for-an-ionic-project-with-android-target

> In Capacitor you are supposed to commit the ios and android folders. They contain their own .gitignore files with the recommended files for iOS and Android.
> 
> They are not build artifacts, if you change icons or configurations (in Info.plist, AndroidManifest.xml, etc) and you delete the folders, those changes will be lost.

**Comment by Hugos68** [comment]
Thanks for the heads up, I haven't played around with iOS and android builds much

**Comment by Hugos68** [comment]
Closed as per #72
