### ISSUE TITLE
[Feature]: add adapter-static

### ISSUE THREAD

**Issue by bluepuma77** [Hugos68/capkit#76]
The [svelte-capacitor-recipe](https://github.com/bersling/svelte-capacitor-recipe) states to use `adapter-static` and also create a `+layout.ts` file. Also some more neat little tricks. Would that be something that `capkit` could do automatically?

**Comment by Hugos68** [comment]
This can definitely be done although I'm not sure if `capkit` would be responsible for this, I'll investigate, thanks for the request.

**Comment by Hugos68** [comment]
Closing this as this would be out of scope of `capkit`.
